import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProductsContextProvider from './contexts/ProductsContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Efortlex Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductsContextProvider>
          {children}
        </ProductsContextProvider>
      </body>
    </html>
  )
}
